name: Build & Push Image

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: registry.cloud360.ca/cloud360/dummy-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASS }}" | docker login registry.cloud360.ca \
            -u "${{ secrets.HARBOR_USER }}" --password-stdin

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest